run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocritic
  disable:
    - wsl
    - lll
    - funlen
    - gomnd
    - gocyclo
    - dupl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G204
      - G304
      - G307
      - G402
      - G404
      - G501
      - G601

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0 